build: ng add
atinc/ngx-tethys pull request #1000
Opened 2020-12-01 02:33 UTC by wszgrcy

2020-12-01 03:13 UTC, why520crazy requested changes

2020-12-01 03:13 UTC, why520crazy commented on schematics/ng-add/index.ts
> +        return tree;
ngx-tethys 这个包没有加进去

2020-12-01 04:08 UTC, why520crazy commented
```
 "test:schematics": "TS_NODE_PROJECT=./tsconfig.schematics.json node --require ts-node/register/transpile-only node_modules/jasmine/bin/jasmine schematics/**/*.spec.ts"
```
我们可以加一个 script `test:schematics` 专门测试 Schematics

2020-12-01 10:01 UTC, why520crazy commented on src/package.json
> +    "rxjs": "*"
peerDependencies 也都指定一下版本号 

```
 "@angular/common": "^9.0.0 || ^10.0.0",
    "@angular/compiler": "^9.0.0 || ^10.0.0",
    "@angular/core":"^9.0.0 || ^10.0.0",
    "@angular/forms":"^9.0.0 || ^10.0.0",
    "rxjs": "^6.5.4"
```

2020-12-01 10:35 UTC, wszgrcy commented on schematics/ng-add/index.spec.ts
> +async function createTestProject(
这个文件夹是同级建立吗?

2020-12-01 10:40 UTC, why520crazy commented
test this please

2020-12-01 12:02 UTC, why520crazy requested changes

2020-12-01 12:02 UTC, why520crazy commented on schematics/ng-add/index.spec.ts
> +async function createTestProject(
> 这个文件夹是同级建立吗?

和 ng-add 同级， `schematics/testing`

2020-12-02 01:41 UTC, why520crazy approved these changes

2020-12-02 01:42 UTC, merged