feat(uploader): add max-size for upload #WIK-2073
atinc/ngx-tethys pull request #1069
Opened 2020-12-25 02:29 UTC by huanhuanwa

2020-12-25 03:27 UTC, pubuzhixing8 commented on src/uploader/file-drop.component.ts
> +        sizeThreshold: 200,
这个还有用么？

2020-12-25 09:38 UTC, why520crazy requested changes

2020-12-25 09:38 UTC, why520crazy commented on src/uploader/constant.ts
> +}
ErrorData 改成 `ThyFileSizeExceedsContext` 去掉 ERROR_TYPES 和 ErrorData， 同时创建一个 types.ts 文件把 ThyFileSizeExceedsContext 移动过去
```
{
   files: File[];
   exceedsFiles: [];
   nativeEvent?: Event;
   sizeThreshold?: number;
}
```

2020-12-25 09:38 UTC, why520crazy commented on src/uploader/uploader.config.ts
> +                console.error('size exceeds', event);
默认的错误日志只需要把超过文件大小的文件和大小打印出来，更加友好的错误提示

2020-12-25 09:38 UTC, why520crazy commented on src/uploader/uploader.config.ts
> +                console.error('size exceeds', event);
这里面已经不依赖其他服务了，可以把 useFactory 去掉

2020-12-25 09:39 UTC, why520crazy commented
最后最好补充一个测试测试新增的case

2020-12-25 10:30 UTC, why520crazy requested changes

2020-12-25 10:30 UTC, why520crazy commented on src/uploader/file-drop.component.ts
> +    @Input() thySizeExceedsHandler: (data: ThyFileSizeExceedsContext) => {};
thySizeExceedsHandler 函数也在 types 中加一个类型 type ThySizeExceedsHandler = (data: ThyFileSizeExceedsContext): File[] | undefined;

2020-12-25 10:33 UTC, why520crazy requested changes

2020-12-25 10:33 UTC, why520crazy commented on src/uploader/file-drop.component.ts
> +        return this.thySizeThreshold ? this.thySizeThreshold : this.defaultConfig.thySizeThreshold;
你这判断是有问题，我传了一个 0 其实你会当做默认值处理，应该只有 undefined 才会选择默认值

2020-12-25 10:35 UTC, why520crazy requested changes

2020-12-25 10:35 UTC, why520crazy commented on src/uploader/examples/basic/basic.component.ts
> +        }
示例中的 sizeExceedsHandler 没有更新

2020-12-25 10:35 UTC, why520crazy commented on src/uploader/file-select.component.ts
> +import { UploaderBase } from './uploader-base';
这个不是 UploaderBase， 应该是 FileSelectBaseComponent

2020-12-28 01:51 UTC, why520crazy requested changes

2020-12-28 01:51 UTC, why520crazy commented on src/uploader/uploader.config.ts
> +    thySizeExceedsHandler?: (event: ThyFileSizeExceedsContext) => {};
使用  ThySizeExceedsHandler 类型

对于 Config 的变量建议去掉 thy 前缀
```
 sizeThreshold?: number;
 sizeExceedsHandler?: ThySizeExceedsHandler;
```

2020-12-28 01:51 UTC, why520crazy commented on src/uploader/types.ts
> +export type ThySizeExceedsHandler = (data: ThyFileSizeExceedsContext) => File[] | undefined;
估计返回值得加一个 void

2020-12-28 01:51 UTC, why520crazy commented on src/uploader/file-select-base.ts
> +        thySizeExceedsHandler?: (sizeExceedData: ThyFileSizeExceedsContext) => {}
使用 ThySizeExceedsHandler 类型

2020-12-28 01:51 UTC, why520crazy commented on src/uploader/examples/basic/basic.component.ts
> +    sizeExceedsHandler = (event: { files: File[]; exceedsFiles: File[]; nativeEvent: Event; sizeThreshold: number }) => {
这里使用 ThyFileSizeExceedsContext 类型或者 ThySizeExceedsHandler

2020-12-28 01:51 UTC, why520crazy commented on src/uploader/api/zh-cn.js
> +                type: '(data: ThyFileSizeExceedsContext)=>{}',
这个返回值和 ThySizeExceedsHandler 的不一样

2020-12-28 01:51 UTC, why520crazy commented on src/uploader/uploader.config.ts
> +            });
这里建议是打印一个错误日志包含所有文件
```
const exceedsFilesMessage = event.exceedsFiles.map((item)=> {
    return `file: ${item}, size: ${item.size}`
} )
console.error(`some files(${exceedsFilesMessage}) size exceeds threshold${event.sizeThreshold}`);
```

2020-12-28 01:52 UTC, why520crazy commented
需要在 index 中导出 types.ts 和 config.ts 的类型，否则 build 会报错，你可以试试

2020-12-28 03:25 UTC, why520crazy approved these changes

2020-12-28 03:28 UTC, merged