fix(dialog): support custom okText (#INFR-1880)
atinc/ngx-tethys pull request #1227
Opened 2021-04-21 05:49 UTC by minlovehua

2021-04-21 06:04 UTC, why520crazy requested changes

2021-04-21 06:04 UTC, why520crazy commented on src/dialog/test/dialog.spec.ts
> +                const confirmBtn = getElementByDialogContainer('.thy-confirm-footer button:first-child');
这个地方最好是封装一个函数， `getConfirmButtons` 返回确认和取消的按钮，那么在测试用例中可以直接使用会更好，只是建议，不强制。

```
const { okButton, cancelButton } = getConfirmButtons();
```

2021-04-21 06:12 UTC, minlovehua commented on src/dialog/test/dialog.spec.ts
> +                const confirmBtn = getElementByDialogContainer('.thy-confirm-footer button:first-child');
thank you

2021-04-22 05:37 UTC, why520crazy approved these changes

2021-04-22 05:42 UTC, why520crazy requested changes

2021-04-22 05:42 UTC, why520crazy commented on src/dialog/confirm/confirm.component.ts
> +        this.defaultConfig = this.options ? { ...this.defaultConfig, ...this.options } : this.defaultConfig;
这个地方直接使用如下代码即可，因为当判断了以后测试覆盖率降低了，因为没有测试 options 是空的情况
```
this.defaultConfig = { ...this.defaultConfig, ...this.options };
```

2021-04-22 05:50 UTC, merged