feat(input-number): add input-number component #INFR-240
atinc/ngx-tethys pull request #1289
Opened 2021-06-24 11:56 UTC by MissLixf

2021-07-06 05:40 UTC, why520crazy requested changes

2021-07-06 05:40 UTC, why520crazy commented on src/input-number/styles/input-number.scss
> +.input-number {
样式加上 thy, `thy-input-number`

2021-07-06 05:40 UTC, why520crazy commented
整体没有什么大问题，可以补充测试和文档了

2021-12-21 06:06 UTC, luxiaobei commented on src/input-number/doc/zh-cn.md
> +subtitle: 输入框
数字输入框

2021-12-21 06:06 UTC, luxiaobei commented on src/input-number/doc/zh-cn.md
> +- 当需要获取标准数值时。
当需要获取标准数值时。

2021-12-21 09:03 UTC, luxiaobei approved these changes

2021-12-21 09:03 UTC, luxiaobei approved these changes

2021-12-21 09:04 UTC, luxiaobei approved these changes

2021-12-21 11:42 UTC, merged