test(strength): add strength test(#INFR-1841)
atinc/ngx-tethys pull request #1294
Opened 2021-06-29 10:37 UTC by xinglu01

2021-06-29 10:42 UTC, why520crazy requested changes

2021-06-29 10:42 UTC, why520crazy commented on src/strength/test/strength.component.spec.ts
> +    let StrengthElementChildLevel: any;
变量命名使用小写字符开头的驼峰，禁止写 any 类型

2021-06-29 10:43 UTC, why520crazy commented
建议把 自定义和正常使用的测试用例分开，现在全在一起很难读懂

2021-06-30 01:55 UTC, luxiaobei approved these changes

2021-06-30 02:43 UTC, why520crazy approved these changes

2021-06-30 02:43 UTC, merged