fix(shared): The listening event name of ThyStopPropagationDirective component must be a string (#IN…
atinc/ngx-tethys pull request #1410
Opened 2021-12-13 11:04 UTC by minlovehua

…FR-2453)

2021-12-14 01:35 UTC, why520crazy requested changes

2021-12-14 01:35 UTC, why520crazy commented on src/shared/directives/thy-stop-propagation.directive.ts
> +            this._eventName = value ? value.toString() : 'click';
这个最好加一个判断，当 `value` 不是 `string` 的时候不用赋值给 _eventName， 绑定事件的时候如果 _eventName 为 false 不绑定事件即可。
最后补充一个测试。

2021-12-14 10:01 UTC, why520crazy requested changes

2021-12-14 10:01 UTC, why520crazy commented on src/shared/directives/thy-stop-propagation.directive.ts
> +            this._eventName = value && typeof value === 'string' ? value : 'click';
isStopPropagation 是不是继续保留比较好，逻辑清晰一点，现在这样做也没有问题。

其次就是当 value 传入 true 或者 `true` 的时候是不是就没有必要绑定事件了

2021-12-15 06:00 UTC, why520crazy requested changes

2021-12-15 06:00 UTC, why520crazy commented on src/shared/directives/thy-stop-propagation.spec.ts
> +            fixtureInstance.isStopPropagation = 'aaa';
这个地方传了 aaa 后，绑定了 aaa 的事件，那么 click 也会触发吗？怎么没有调用呢

2021-12-15 11:23 UTC, minlovehua commented on src/shared/directives/thy-stop-propagation.spec.ts
> +            fixtureInstance.isStopPropagation = 'aaa';
确实有问题，传入任意字符串，click事件都阻止了冒泡。我研究研究

2021-12-23 04:45 UTC, why520crazy approved these changes

2021-12-23 04:46 UTC, merged