fix(progress): change background and add test and example #INFR-2451
atinc/ngx-tethys pull request #1413
Opened 2021-12-15 07:36 UTC by zhaidong9087

2021-12-15 07:54 UTC, MissLixf commented on src/progress/progress.component.ts
> +    computedThyMax: number;
barsTotalValue

2021-12-15 08:13 UTC, zhaidong9087 commented on src/progress/progress.component.ts
> +    computedThyMax: number;
ok

2021-12-17 09:08 UTC, why520crazy requested changes

2021-12-17 09:08 UTC, why520crazy commented on src/progress/progress.component.ts
> +            this.value = [...(value as ThyStackedValue[])];
这里 if 和 else 都赋值一个 value 干嘛，为了下面有类型的话可以使用 this.value as ThyStackedValue[]，还有就是当 isStacked 最好判断一下 value 是数组才执行这里面的逻辑，不是数组 throw 一个错误， `thyValue must be array for stacked mode.`

2021-12-17 09:08 UTC, why520crazy commented on src/progress/progress.component.ts
> +    computedRemainingValue() {
这个函数的命名时态有问题，computed 是一个过去分词。不是动词，改成`calculateRemainingValue`

2021-12-21 09:41 UTC, why520crazy approved these changes

2021-12-21 09:41 UTC, merged