fix(date-picker): date picker support shortcut options #INFR-2521
atinc/ngx-tethys pull request #1442
Opened 2022-01-17 07:29 UTC by MissLixf

2022-01-17 10:53 UTC, why520crazy commented on src/date-picker/abstract-picker.component.ts
> +    @Input() thyCustomShortcut: ShortcutOptionInfo[];
这个最好改成 `thyShortcutRanges`

2022-01-18 09:44 UTC, why520crazy requested changes

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/date-picker.config.ts
> +export const THY_DATE_PICKER_SHORTCUT_CONFIG = new InjectionToken<ThyDatePickerShortcutConfig>('thy-date-picker-shortcut-config');
改成 `THY_DATE_PICKER_CONFIG` 吧，将来扩展其他的配置也方便

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/date-picker.config.ts
> +        presetShortcutRanges: [
这个改成 `shortcutRanges` 吧，默认配置的都是预设的

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/date-picker.config.ts
> +                begin: new TinyDate().startOfDay().getTime() - 3600 * 1000 * 24 * 6,
这里的 begin 和 end 需要改成函数，否则加载 js 的时候这些值就已经确定了，我如果没有刷新，到明天再打开时间就不对，应该是打开选择框的时候计算 begin 和 end

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/range-picker.component.ts
> +                this.shortcutRanges = [...this.datePickerShortcutConfig.presetShortcutRanges, ...ranges];
当用户传了 ranges 以用户传的为主，不要把配置的追加上

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/range-picker.component.ts
> +        @Inject(THY_DATE_PICKER_SHORTCUT_CONFIG) private datePickerShortcutConfig: ThyDatePickerShortcutConfig
需要把用户配置的和默认的配置合并，否则如果用户只配置一个 `shortcutPosition`, ranges 就没有了。
建议写一个 `ThyDatePickerConfig` 的服务，合并和获取配置在这个服务中统一处理。

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/range-picker.directive.ts
> +    }
这里的逻辑和 `ThyRangePickerComponent` 中的一样，建议想办法抽取一下，不要重复写两遍

2022-01-18 09:44 UTC, why520crazy commented on src/date-picker/abstract-picker.component.ts
> +    shortcutRanges: ShortcutRange[] = [];
shortcutRanges 默认应该是取配置文件中的，不是空。

2022-01-18 09:52 UTC, why520crazy requested changes

2022-01-18 09:52 UTC, why520crazy commented on src/date-picker/abstract-picker.component.ts
> +    @Output() readonly thyShortcutClick = new EventEmitter<ShortcutRange>();
这个建议改成 `thyShortcutValueChange` 同时 Emit 的对象改成 `{value: CompatibleDate, triggerRange: ShortcutRange}` 这样将来可扩展。

2022-01-18 09:52 UTC, MissLixf commented on src/date-picker/abstract-picker.component.ts
> +    shortcutRanges: ShortcutRange[] = [];
那是不是得加个参数thyShowShortcut，判断否显示shortcut，现在使用shortcutRanges.length去判断

2022-01-19 01:42 UTC, why520crazy commented on src/date-picker/abstract-picker.component.ts
> +    shortcutRanges: ShortcutRange[] = [];
> 判断否显示shortcut，

用和不用小欧行，没有传，默认采用配置文件中的，如果手动传了 false 就是空

2022-01-19 05:53 UTC, why520crazy requested changes

2022-01-19 05:53 UTC, why520crazy commented on src/date-picker/lib/popups/date-popup.component.ts
> +    shortcurClick(shortcutRange: ShortcutRange) {
`shortcutClick` 单词错误，同事建议改成 `shortcutSetValue` ，这个地方需要触发 ngModelChange 的

2022-01-19 05:53 UTC, why520crazy commented on src/date-picker/range-picker.component.spec.ts
> +        }));
需要验证是否触发了 ngModeChange 事件

2022-01-19 05:53 UTC, why520crazy commented on src/date-picker/date-picker.service.ts
> +export class DatePickerConfig {
可以改成 `ThyDatePickerConfigService`， 这样就避免和 `ThyDatePickerConfig` 冲突了

2022-01-19 05:53 UTC, why520crazy commented on src/date-picker/standard-types.ts
> +export interface ShortcutValueChange {
对外暴露的对象最好都加上 Thy 前缀， `ThyShortcutValueChange`,`ThyShortcutPosition`, `ThyShortcutRange`

2022-01-19 07:49 UTC, why520crazy approved these changes

2022-01-19 07:50 UTC, merged