test(popover): improve popover test coverage (#INFR-2588)
atinc/ngx-tethys pull request #1455
Opened 2022-02-10 10:42 UTC by minlovehua

2022-02-11 08:06 UTC, why520crazy requested changes

2022-02-11 08:06 UTC, why520crazy commented on src/popover/test/popover.service.spec.ts
>      });
这里建议把 btnElement1 - btnElement4 的 click 去掉，现在这种方式测试可读性太差。
可以直接把 template1 - template4 在测试组件中暴露出来，然后测试的时候直接使用 popover.open 调用，这样可以直观的看到 config 配置，而不用模拟点击按钮。

```ts
 this.popover.open(template1, {
            btn1,
            manualClosure: true
        });
```

只是建议，可以不用修改。

2022-02-11 08:30 UTC, minlovehua commented on src/popover/test/popover.service.spec.ts
>      });
👍🏻

2022-02-14 03:22 UTC, why520crazy approved these changes

2022-02-14 03:22 UTC, merged