test(layout): improve layout test coverage、fix sidebar thyIsDraggableWidth、docs sidebar thyIsDraggableWidth (#INFR-2576)
atinc/ngx-tethys pull request #1467
Opened 2022-02-17 10:14 UTC by minlovehua

2022-02-18 10:00 UTC, why520crazy requested changes

2022-02-18 10:05 UTC, minlovehua commented on src/layout/sidebar.component.ts
> +            setTimeout(() => {
还有，测试我还没补完，还在补充

2022-02-21 07:57 UTC, why520crazy requested changes

2022-02-21 07:57 UTC, why520crazy commented on src/layout/sidebar.component.ts
> +            setTimeout(() => {
这个最好去除  setTimeout 的逻辑，第一次通过 onInit 钩子做初始化的事情，当再次设置 thyIsDraggableWidth 的时候就已经有值了，再直接操作

2022-02-25 05:47 UTC, why520crazy requested changes

2022-02-25 05:47 UTC, why520crazy commented on src/layout/sidebar.component.ts
>          }
这里有2个问题：
1. 第一次渲染的时候比你那个不会设置 pointer-events
2. 第二次设置为 false 的时候不会重置回去

建议这个地方应该保存一下 `isDraggableWidth` 变量，然后抽取一个函数 setDraggable 设置 pointer-events，thyIsDraggableWidth 的 set 访问器和 ngOnInit() 中调用 `setDraggable`

```ts
setDraggable() {
  if(!this.dragRef) { return; }
  
  this.renderer.setStyle(this.dragRef.nativeElement, 'pointer-events',  this.isDraggableWidth ? 'all': '');
  
}

```

2022-02-25 05:55 UTC, why520crazy commented
此次提交优先是修复缺陷，所以 Commit Message 建议修改为：
`fix(layout): update dragRef's pointer-events to all when thyIsDraggableWidth  is true, and improve docs and test cases #INFR-2610`

2022-02-25 06:27 UTC, why520crazy approved these changes

2022-02-25 06:28 UTC, merged