fix(progress): stacked model when value is change #INFR-2608
atinc/ngx-tethys pull request #1473
Opened 2022-02-21 10:09 UTC by zhaidong9087

2022-02-21 10:43 UTC, why520crazy requested changes

2022-02-21 10:43 UTC, why520crazy commented on src/progress/progress.component.ts
> +        debugger;
去掉 debugger

2022-02-21 10:43 UTC, why520crazy commented on src/progress/progress.component.ts
> +    isChangeMaxFlag = true;
这个变量可以去掉，`_thyMax` 不为空就可以判断是否传入了 max， 当然是我的话会改成 `private settedMax: number` 不改也没有问题

2022-02-21 10:43 UTC, why520crazy commented on src/progress/progress.component.ts
>          if (max < this.barsTotalValue) {
这里建议抽取一个 setMax 函数，把相关逻辑抽取出来

2022-02-21 10:44 UTC, zhaidong9087 commented on src/progress/progress.component.ts
> +        debugger;
ok

2022-02-21 10:45 UTC, zhaidong9087 commented on src/progress/progress.component.ts
>          if (max < this.barsTotalValue) {
好，我再改一下

2022-02-22 05:56 UTC, why520crazy requested changes

2022-02-22 05:56 UTC, why520crazy commented on src/progress/progress.component.ts
> +        this.setMax(max);
这里的逻辑是有问题，当 thyMax 二次修改后，并没有对 settedMax 进行重新修改。
这里建议不管如何都要调用
```
this.settedMax = max;

// 如果采纳下面建议的话需要调用 calculateMax 重新计算 max 值
this.calculateMax();
```

2022-02-22 05:56 UTC, why520crazy commented on src/progress/progress.component.ts
> +    }
目前这块的可读性不是很好，代码比较难读，可以把 setMax 代码改成  calculateMax， 逻辑如下所示：会根据 settedMax 和 barsTotalValue 重新计算 max 值，然后调用每个 bar 重新计算百分比。
```
calculateMax() {
        if (isNumber(this.settedMax) && this.settedMax > 0) {
            this.max = this.settedMax;
        } else {
            this.max = this.barsTotalValue;
        }
        if (this.max < this.barsTotalValue) {
           this.max = this.barsTotalValue;
        }
        this.max = max;
        this.bars.forEach(bar => {
            bar.recalculatePercentage();
        });
    }
```

2022-02-22 05:56 UTC, why520crazy commented on src/progress/progress.component.ts
> +                this.max = this.settedMax;
此处直接调用 `this.calculateMax()` 即可

2022-02-22 05:58 UTC, zhaidong9087 commented on src/progress/progress.component.ts
> +                this.max = this.settedMax;
ok

2022-02-22 06:11 UTC, zhaidong9087 commented on src/progress/progress.component.ts
> +                this.max = this.settedMax;
<thy-progress class="mt-2" thyType="info" [thyMax]="max" [thyValue]="value1" ></thy-progress>
<button (click)="test120()">120</button>
<button (click)="test90()">90</button>
<button (click)="test45()">40</button>

  max = 90;
 value1 = [
        {
            value: 30,
            color: '#2cccda'
        }
    ];

    test120() {
        this.value1 = [
            {
                value: 120,
                color: '#2cccda'
            }
        ];
    }

    test90() {
        this.value1 = [
            {
                value: 90,
                color: '#2cccda'
            }
        ];
    }

    test45() {
        this.value1 = [
            {
                value: 40,
                color: '#2cccda'
            }
        ];
    }

2022-02-22 06:14 UTC, zhaidong9087 commented on src/progress/progress.component.ts
> +                this.max = this.settedMax;
我写的这个例子max=90 初始值为30那么宽度为33.33%，然后值变成120，宽度变为100，然后值为90，还是100，最后我的值是45，期望的应该是50%呀。这个逻辑相当于只改变了最大的值为max，后面我的值小于了max，你这里不会给我变

2022-02-23 06:46 UTC, why520crazy approved these changes

2022-02-23 06:47 UTC, merged