feat(popover): support autoAdaptive  zd/#INFR-2794
atinc/ngx-tethys pull request #1615
Opened 2022-04-27 03:57 UTC by zhaidong9087

2022-04-27 06:59 UTC, why520crazy requested changes

2022-04-27 06:59 UTC, why520crazy commented on src/popover/examples/basic/basic.component.html
> +
建议新增一个单独的示例 `auto-adaptive` 不要在 basic 示例中加异步加载的任务，示例最好这次改为 docgeni 最新的模块加载方式，参考： dropdown 或者 progress。

2022-04-27 06:59 UTC, why520crazy commented on src/popover/test/popover.service.spec.ts
> +            expect(popoverRef.updatePosition()).toBeTruthy();
这里的断言不是应该判断是否调用了 `updatePosition` 吗？或者断言新的位置是否符合预期

2022-04-27 06:59 UTC, why520crazy commented on src/popover/popover.config.ts
> +    /**  autoAdaptive is true when height change can auto update position */
这里不仅仅高度变化会更新位置，宽度变化也会，你在测试中可以补充一个用例（不强制）

2022-04-27 06:59 UTC, why520crazy commented on src/popover/popover.directive.ts
> +    @Input() autoAdaptive = false;
所有的 @Input 需要以 thy 开头，指令的 API 没有加上。

2022-04-27 07:03 UTC, zhaidong9087 commented on src/popover/test/popover.service.spec.ts
> +            expect(popoverRef.updatePosition()).toBeTruthy();
判断这个方法是否调用，expect(Spy).toHaveBeenCalled();这个 Spy 不知道咋定义，有好的建议吗

2022-04-27 07:03 UTC, zhaidong9087 commented on src/popover/popover.config.ts
> +    /**  autoAdaptive is true when height change can auto update position */
嗯  ，好

2022-04-27 07:03 UTC, zhaidong9087 commented on src/popover/popover.directive.ts
> +    @Input() autoAdaptive = false;
嗯

2022-04-27 07:03 UTC, zhaidong9087 commented on src/popover/examples/basic/basic.component.html
> +
嗯，我在修改修改

2022-04-27 09:40 UTC, why520crazy commented on src/popover/test/popover.service.spec.ts
> +            expect(popoverRef.updatePosition()).toBeTruthy();
> 判断这个方法是否调用，expect(Spy).toHaveBeenCalled();这个 Spy 不知道咋定义，有好的建议吗

你自己搜索如何创建 spy 模拟测试，我们系统到处都是 spy

2022-04-28 05:15 UTC, why520crazy requested changes

2022-04-28 05:15 UTC, why520crazy commented on src/popover/doc/zh-cn.md
> +category: display
这个为什么要改成 `display` ？ 应该还是属于 feedback

2022-04-28 05:15 UTC, why520crazy commented on src/popover/examples/auto-adaptive/auto-adaptive.component.html
> +<div class="demo-buttons d-flex mt-3">
autoAdaptive 示例去掉各种参数，独立一个示例表示`自动适配`就不需要其他参数干扰了。

2022-04-28 05:15 UTC, why520crazy commented on src/popover/examples/auto-adaptive/auto-adaptive.component.html
> +  </button>
这个示例主要是 autoAdaptive，所以不需要命名为 Async Fetch Data，直接改为 Open

2022-04-28 05:15 UTC, why520crazy commented on src/popover/popover-container.component.ts
> +    private destroy$ = new Subject<void>();
父类中已经有 `containerDestroy`，建议直接改为 `destroy$` 直接使用，无需再定义一个，调用`super.destroy();`就已经 next

2022-04-28 05:15 UTC, why520crazy commented on src/popover/popover-container.component.ts
> +                        .pipe(debounceTime(100), takeUntil(this.destroy$))
这里去除`debounceTime(100)` , ContentObserver 底层使用了 MutationObserver 本身不会在宽高变化的时候立即执行，已经考虑了性能的问题了，不需要自行处理

2022-04-28 05:15 UTC, why520crazy commented on src/popover/test/popover.service.spec.ts
> +            let info = '未执行';
测试中文案最好不要使用中文，示例也是

2022-04-28 05:15 UTC, why520crazy commented on src/popover/test/popover.service.spec.ts
> +            popoverRef.containerInstance.updatePosition.subscribe(() => {
这里使用 spyOn( popoverRef.containerInstance, "updatePosition"); 就行了，不需要通过订阅设置值得方式

```
const spyUpdatePosition = spyOn( popoverRef.containerInstance, "updatePosition");
expect(spyUpdatePosition).toHaveBeenCalled();
```

2022-04-28 05:15 UTC, why520crazy commented on src/popover/api/zh-cn.js
> +                description: '是否开启异步加载内容后更新位置',
建议改成： `是否开启自动适配大小模式，开启后当弹出框内容宽高发生变化后自动更新位置`

2022-04-28 05:15 UTC, why520crazy commented on src/popover/doc/zh-cn.md
> +## basic
文档的标题如果是英文，首字母大写， 『Basic 』或者中文 『基本示例』

2022-04-28 05:57 UTC, zhaidong9087 commented on src/popover/test/popover.service.spec.ts
> +            popoverRef.containerInstance.updatePosition.subscribe(() => {
![image](https://user-images.githubusercontent.com/22216554/165686520-767bedde-9c50-43bf-a107-84faed9e69f3.png)

2022-04-28 05:57 UTC, zhaidong9087 commented on src/popover/test/popover.service.spec.ts
> +            popoverRef.containerInstance.updatePosition.subscribe(() => {
这样用不可以

2022-04-29 03:29 UTC, merged