fix(menu): modify more icon m-l #INFR-3717
atinc/ngx-tethys pull request #2006
Opened 2022-07-20 11:04 UTC by wangyuan-ky

2022-07-20 11:11 UTC, why520crazy requested changes

2022-07-20 11:11 UTC, why520crazy commented on src/menu/styles/menu.scss
> +            display: none;
改成这样后鼠标移动上去会有闪烁，这个和设计师确认过？

2022-07-20 11:12 UTC, wangyuan-ky commented on src/menu/styles/menu.scss
> +            display: none;
嗯嗯，跟王老师确认过了~

2022-07-21 01:46 UTC, why520crazy approved these changes

2022-07-21 01:46 UTC, merged