test(tabs): test coverage to 100% #INFR-4017
atinc/ngx-tethys pull request #2062
Opened 2022-08-08 13:00 UTC by minlovehua

2022-08-09 01:24 UTC, why520crazy requested changes

2022-08-09 01:24 UTC, why520crazy commented on src/tabs/test/tabs.spec.ts
> +            fixture.detectChanges();
这个测试断言严格来说是有问题的，如果没有执行 thyActiveTabChange 那么也会测试通过，最好的是点击之后断言

2022-08-10 01:48 UTC, minlovehua commented on src/tabs/test/tabs.spec.ts
> +            fixture.detectChanges();
好的，我修改修改

2022-08-10 05:50 UTC, why520crazy approved these changes

2022-08-10 05:50 UTC, merged