feat(typography): add thy-text(#INFR-4313)
atinc/ngx-tethys pull request #2104
Opened 2022-08-22 11:25 UTC by mengshuicmq

2022-08-22 11:35 UTC, why520crazy requested changes

2022-08-22 11:35 UTC, why520crazy commented on src/typography/styles/typography.scss
> +    }
这里可以先使用 text-xxxx 的工具样式，暂时不用加 thy-text-***

2022-08-22 11:35 UTC, mengshuicmq commented on src/typography/styles/typography.scss
> +    }
好的

2022-08-22 11:36 UTC, why520crazy requested changes

2022-08-22 11:36 UTC, why520crazy commented on src/typography/examples/text/text.component.html
> +<thy-text thyColor="#c9584e">This is a text</thy-text>
示例直接把所有颜色依次写上，不要使用表单选择

2022-08-24 03:06 UTC, why520crazy requested changes

2022-08-24 03:06 UTC, why520crazy commented on src/typography/text-color.directive.ts
> +            this.updateHostClassService.updateClass([`text-${this.color}`]);
这里有个小问题，从自定义颜色改变为 primary 的时候，原有的颜色没有被清楚

2022-08-24 03:06 UTC, why520crazy commented on src/typography/styles/typography.scss
> +    }
text-* 的样式， scss 文件 styles/bootstrap/utilities/_text.scss 已经存在，这里不用写了

2022-08-24 03:06 UTC, why520crazy commented on src/typography/examples/text/text.component.html
> +<span class="mr-3" thyTextColor="placeholder">placeholder</span>
mr-3 去掉，采用自定义组件样式设置 span 的间距，

预设文本颜色和自定义文本颜色的分类采用 thy-divider 组件实现或者去掉分类，
直接修改 <thy-text thyTextColor="#c9584e">This is a text</thy-text> 为

```
<thy-text thyTextColor="#c9584e">Custom Color #c9584e</thy-text>
```

2022-08-24 07:20 UTC, why520crazy approved these changes

2022-08-24 07:20 UTC, why520crazy commented on src/styles/variables.scss
> +);
这个定义先去掉吧，没有用到

2022-08-24 07:43 UTC, mengshuicmq commented on src/styles/variables.scss
> +);
去掉了

2022-08-24 07:43 UTC, why520crazy approved these changes

2022-08-24 07:44 UTC, merged