fix(color-picker): fix closeAll bug #INFR-4807
atinc/ngx-tethys pull request #2229
Opened 2022-09-29 07:57 UTC by cmm-va

2022-09-29 08:02 UTC, WBbug commented on src/color-picker/default-panel.component.ts
> +
少个@Input()

2022-09-29 08:06 UTC, cmm-va commented on src/color-picker/default-panel.component.ts
> +
> 

弹框传入的好像不需要input 呀 ，我记错了吗？

2022-09-29 08:13 UTC, WBbug commented on src/color-picker/default-panel.component.ts
> +
需要的

2022-09-29 08:34 UTC, WBbug approved these changes

2022-09-29 08:55 UTC, huanhuanwa commented on src/color-picker/color-picker.component.ts
>      @HostListener('click', ['$event'])
click 事件使用 fromEvent 监听，放在 runOutsideAngular 里执行吧，可以减少脏检查的次数，记得销毁的时候取消监听。

2022-09-29 08:55 UTC, huanhuanwa commented on src/color-picker/default-panel.component.ts
> +        this.popoverRef?.close();
这里的 popover 是不是没有用？

2022-09-29 08:55 UTC, huanhuanwa commented on src/color-picker/default-panel.component.ts
> +        this.popoverRef = this.thyPopover.open(ThyPickerPanelComponent, {
1. 弹出更多颜色选择的时候，参数应该加上` hasBackdrop: false`, 不然就无法选中默认面板中的颜色了。
2. 参数加上 viewContainerRef，这样父面板关闭的时候子面板会一起关闭。

2022-09-29 10:55 UTC, huanhuanwa commented on src/color-picker/color-picker.component.ts
> +        this.destroy$.next();
再加个 this.destroy$.complete();

2022-09-30 05:53 UTC, why520crazy requested changes

2022-09-30 05:53 UTC, why520crazy commented on src/color-picker/color-picker.component.ts
> +                    defaultPanelPopover.close();
这里加一个 closeCallback 其实就是要关闭当前的 Popover，有点多次一举，我们可以直接在 `ThyColorDefaultPanelComponent` 组件中注入 `PopoverRef`, 直接调用这个 ref.close 关闭即可。

还有就是这个 panel 叫 Default 不是太好，我们有两个 color-picker 的 panel，这个 default 应该直接是 color-picker-panel，另一个应该是自定义颜色的 picker panel。（这是内部使用的，也不是很关键）

2022-10-11 02:22 UTC, merged