feat(input): add 'form-control-active' when thy-input-search focus #I…
atinc/ngx-tethys pull request #2304
Opened 2022-11-04 01:56 UTC by xiangergou

…NFR-5167

2022-11-04 02:04 UTC, walkerkay approved these changes

2022-11-04 02:04 UTC, walkerkay commented on src/input/input-search.component.ts
> +    @HostBinding('class.form-control-active') _isFocus = false;
为什么要用下划线命名

建议把 @HostBinding 放在 constructor 上面

2022-11-04 02:11 UTC, why520crazy requested changes

2022-11-04 02:11 UTC, why520crazy commented on src/input/input-search.component.ts
> +    @HostBinding('class.form-control-active') isFocus = false;
1. 建议直接在元数据 `host` 中写 `'[class.form-control-active]': 'focused` 设置 `focused` 样式
2. 建议加一个测试用例

@walkerkay 可以不？

2022-11-04 03:59 UTC, why520crazy requested changes
LGTM

2022-11-04 03:59 UTC, why520crazy commented on src/input/test/input-search.spec.ts
> +        expect(searchElement.classList.contains('form-control-active')).toBe(true);
光标移走后断言一下这个样式不存在！

2022-11-06 13:37 UTC, walkerkay approved these changes

2022-11-07 01:22 UTC, why520crazy approved these changes

2022-11-07 01:23 UTC, merged