fix(slide): slide support open multiple slideRef #INFR-5263
atinc/ngx-tethys pull request #2335
Opened 2022-11-15 07:44 UTC by yxb941006

2022-11-16 08:50 UTC, luxiaobei commented on src/slide/slide.service.ts
> +            this.removeOpenedOverlay(openedOverlay);
openedOverlay.close()

2022-11-16 09:13 UTC, yxb941006 commented on src/slide/slide.service.ts
> +            this.removeOpenedOverlay(openedOverlay);
afterClosed是异步触发的，执行openOverlay之后才会触发，但是在执行openOverlay时会判断当前id已存在，所以在这里还是手动触发一下removeOpenedOverlay

2022-11-23 03:11 UTC, why520crazy requested changes

2022-11-23 03:11 UTC, why520crazy commented on src/slide/api/zh-cn.js
> +                name: 'isCloseLatest',
这个参数建议改为 `disableCloseLatest` 默认是 `false`

2022-11-23 03:50 UTC, why520crazy approved these changes

2022-11-23 03:51 UTC, merged

2022-11-23 09:28 UTC, luxiaobei commented on src/slide/slide.service.ts
> +        if (!config.disableCloseLatest) {
这里config需要 将 defaultConfig 和 config 合并后判断吧