feat(form): add more way to validate form #INFR-2972
atinc/ngx-tethys pull request #2370
Opened 2022-11-25 10:06 UTC by xiangergou

2022-12-29 02:23 UTC, why520crazy requested changes
这个代码没有问题，测试需要修复一下， Lint 挂了，如果补充一下测试是最好的

2022-12-29 02:25 UTC, xiangergou commented
> 这个代码没有问题，测试需要修复一下， Lint 挂了，如果补充一下测试是最好的

好的 我尽快补下

2023-01-28 09:33 UTC, xiangergou commented
@why520crazy 补上了海大神

2023-01-30 04:01 UTC, why520crazy requested changes

2023-01-30 04:01 UTC, why520crazy commented on src/form/form-validator.service.ts
> +                    console.log(item, 3);
移除这个 console.log

2023-01-30 05:34 UTC, xiangergou commented on src/form/form-validator.service.ts
> +                    console.log(item, 3);
额 疏忽了。。 移除掉了

2023-01-30 08:03 UTC, merged