feat(cdk): add ThyHotkeyDirective and  ThyHotkeyDispatcher #INFR-5572
atinc/ngx-tethys pull request #2388
Opened 2022-12-04 14:12 UTC by walkerkay

2022-12-05 02:42 UTC, walkerkay commented
1. cdk 增加 hotkey 模块，提供 ThyHotkeyDirective  和 ThyHotkeyDispatcher 
2. ngx-tethys/core/event-dispatcher.ts 移到了 cdk/event （hotkey依赖这个，也可以不依赖，但是感觉 event-dispatcher.ts 放 cdk 更合适，只不过专门加一个 event 模块是否合适不确定）
3. 增加了 CDK Demo
4. 修复 tsconfig 支持在 ngx-tethys 中引入 @tethys/cdk/*

2022-12-05 08:47 UTC, why520crazy requested changes

2022-12-05 08:47 UTC, why520crazy commented on src/input/examples/pre-suffix/pre-suffix.component.html
> +        <a href="javascript:;" (click)="alert(123)" thyHotkey="Meta+b"><span thyLabel="default">获取验证码</span></a>
这个示例是不是不应该在 input 的 pre-suffix 示例修改？

2022-12-05 08:47 UTC, why520crazy commented on src/input/examples/basic/basic.component.html
> +    <input thyInput thyHotkey="Meta+b,Control+b" [(ngModel)]="value" placeholder="Please type (thyInput)" />
这里也是

2022-12-05 08:47 UTC, why520crazy commented on src/core/event-dispatchers/keyboard-dispatcher.ts
> +import { ThyEventDispatcher } from '@tethys/cdk/event';
我建议把 ThyKeyboardDispatcher 也移动到 CDK event 模块中吧，去掉文件的注释代码，为了兼容加一个 
```ts
export {ThyKeyboardDispatcher} from "@tethys/cdk/event"
```
可以不？

2022-12-05 08:47 UTC, why520crazy commented on cdk/hotkey/hotkey-dispatcher.ts
> +export class ThyHotkeyDispatcher extends ThyEventDispatcher {
这个服务不应该是个私有的吧，在子产品或者 Pro 可以直接使用 `ThyHotkeyDispatcher`

2022-12-05 08:52 UTC, why520crazy requested changes

2022-12-05 08:52 UTC, why520crazy commented on cdk/hotkey/hotkey.directive.ts
> +export class ThyHotkeyDirective implements OnInit, OnDestroy {
这个指令加一个注释设置 `@name thyHotkey `

2022-12-05 08:56 UTC, walkerkay commented on src/core/event-dispatchers/keyboard-dispatcher.ts
> +import { ThyEventDispatcher } from '@tethys/cdk/event';
> ```ts
> ThyKeyboardDispatcher
> ```

可以

2022-12-05 08:58 UTC, walkerkay commented on cdk/hotkey/hotkey-dispatcher.ts
> +export class ThyHotkeyDispatcher extends ThyEventDispatcher {
*  @private
 */

> 这个服务不应该是个私有的吧，在子产品或者 Pro 可以直接使用 `ThyHotkeyDispatcher`

这个是因为文档生成的有问题，所以我标记 private 是为了不生成文档

2022-12-06 02:03 UTC, why520crazy approved these changes

2022-12-06 02:03 UTC, merged