fix(autocomplete): replace thyAutocompleteComponent with thyAutocomplete #INFR-2990
atinc/ngx-tethys pull request #2500
Opened 2023-02-01 06:11 UTC by xiangergou

2023-02-07 06:35 UTC, why520crazy requested changes

2023-02-07 06:35 UTC, why520crazy commented on src/autocomplete/autocomplete.trigger.directive.ts
> +        const activeItem = this.activeOption
这里加 activeOption 的判断逻辑我不确定是否会有问题，加这个判断主要是解决什么问题的？如果是修复某个缺陷记得补充一个测试 case， 有没有问题需要 @pubuzhixing8 看看，我不太了解。

2023-02-07 06:35 UTC, why520crazy commented on src/autocomplete/api/zh-cn.js
> +                name: 'thyAutocomplete',
这里的 thyAutocompleteComponent 和 thyAutocompleteTrigger 建议保留加描述已经废弃。
如果可以的话顺便删除 zh-cn.js 使用注释生成 API 文档，当然是最好的。

2023-02-07 06:35 UTC, why520crazy commented on src/autocomplete/api/zh-cn.js
> +                name: 'thyAutocomplete',
同时测试最好保留一个过去废弃示例的 case 使用，之后彻底移除 thyAutocompleteComponent 的时候一并删除

2023-02-09 09:42 UTC, xiangergou commented on src/autocomplete/autocomplete.trigger.directive.ts
> +        const activeItem = this.activeOption
这个是我偶遇的一个缺陷，本想顺手改了。   
我还原了，完事儿新建个缺陷处理吧。

2023-02-09 10:09 UTC, xiangergou commented on src/autocomplete/api/zh-cn.js
> +                name: 'thyAutocomplete',
@why520crazy  改了海大神

2023-02-15 03:22 UTC, why520crazy requested changes

2023-02-15 03:22 UTC, why520crazy commented on src/autocomplete/autocomplete.component.ts
> +     */
这个组件上最好加注释声明组件名称和描述
```
/**
 * 自动完成组件
 * @name thy-autocomplete
 */
```
包括 thyAutocomplete 指令
```
/**
 * 自动完成触发指令
 * @name thyAutocomplete
 */
```

这个修改了就可以合并了

2023-02-15 11:11 UTC, xiangergou commented on src/autocomplete/autocomplete.component.ts
> +     */
@why520crazy 加好了~

2023-02-16 01:04 UTC, merged