feat(tooltip): add tooltip service and tooltipRef, refactor tooltip directive #INFR-6382
atinc/ngx-tethys pull request #2532
Opened 2023-02-15 11:55 UTC by walkerkay

2023-02-15 12:00 UTC, walkerkay commented
1. 废弃了原先的 TooltipService
2. 新增 ThyTooltipService 
3. 新增了 ThyTooltipRef ，创建成功后会返回 ThyTooltipRef
4. 使用 ThyTooltipService 重构了 TooltipDirective 指令
5. 原先的 ThyTooltipConfig 改为了 ThyTooltipGlobalConfig
6. 新增了 ThyTooltipConfig 用于创建 ThyTooltip 时指定配置参数
7. 删除了 ThyTooltipOptions，合并到了 ThyTooltipConfig 中
8. 重构了文档

新的 Service 的使用
``` ts
export class ExampleComponent implements OnInit {
    @ViewChild('tooltipHost', { static: true , read: ElementRef<HTMLElement>}) tooltipHostElementRef: ElementRef<HTMLElement>;

    private tooltipRef: ThyTooltipRef;

    constructor(private tooltipService: ThyTooltipService) {}

    ngOnInit(): void {
        this.tooltipRef = this.tooltipService.create(this.tooltipHostElementRef, {
            placement: 'top'
        });
        // 展示 Tooltip
        this.tooltipRef.show('Hello, welcome to PingCode', 200);
        // 隐藏 Tooltip 
        this.tooltipRef.hide(200);
    }
}
```

2023-02-16 02:01 UTC, walkerkay commented
> 1. 废弃了原先的 TooltipService
> 2. 新增 ThyTooltipService
> 3. 新增了 ThyTooltipRef ，创建成功后会返回 ThyTooltipRef
> 4. 使用 ThyTooltipService 重构了 TooltipDirective 指令
> 5. 原先的 ThyTooltipConfig 改为了 ThyTooltipGlobalConfig (全局没有使用)
> 6. 新增了 ThyTooltipConfig 用于创建 ThyTooltip 时指定配置参数
> 7. 删除了 ThyTooltipOptions，合并到了 ThyTooltipConfig 中
> 8. 重构了文档
> 
> 新的 Service 的使用
> 
> ```ts
> export class ExampleComponent implements OnInit {
>     @ViewChild('tooltipHost', { static: true , read: ElementRef<HTMLElement>}) tooltipHostElementRef: ElementRef<HTMLElement>;
> 
>     private tooltipRef: ThyTooltipRef;
> 
>     constructor(private tooltipService: ThyTooltipService) {}
> 
>     ngOnInit(): void {
>         this.tooltipRef = this.tooltipService.create(this.tooltipHostElementRef, {
>             placement: 'top'
>         });
>         // 展示 Tooltip
>         this.tooltipRef.show('Hello, welcome to PingCode', 200);
>         // 隐藏 Tooltip 
>         this.tooltipRef.hide(200);
>     }
> }
> ```

2023-02-16 02:26 UTC, why520crazy requested changes

2023-02-16 02:26 UTC, why520crazy commented on src/tooltip/doc/zh-cn.md
> +```
我建议把 <examples /> 移动到服务动态创建上面，因为 服务动态创建 是高级功能，使用的频次会低

2023-02-16 02:26 UTC, why520crazy commented on src/tooltip/doc/zh-cn.md
> +        this.tooltipRef.hide(200);
这里的示例建议补充上销毁 tooltipRef，因为目前的设计只要打开了就会创建 OverlayRef，如果不销毁会导致内存泄露。

我甚至有个想法就是在 hide 的时候自动销毁，只有 thyTooltipDirective 的时候指定手动销毁，这样避免通过 ThyTooltipService 打开的时候忘记销毁

2023-02-16 03:57 UTC, why520crazy approved these changes

2023-02-17 05:43 UTC, merged