fix(date-range): the previous date range and the next date range should be connectable when unit of step is month #INFR-2425
atinc/ngx-tethys pull request #2723
Opened 2023-06-22 08:38 UTC by minlovehua

2023-07-07 09:54 UTC, Guoxiin requested changes

2023-07-07 09:54 UTC, Guoxiin commented on src/date-range/date-range.component.ts
> +                        begin: getUnixTime(startOfDay(addMonths(beginDate, -1 * interval))),
不用加 startOfDay，addMonths 返回的就是 00:00:00

2023-07-07 09:54 UTC, Guoxiin commented on src/date-range/date-range.component.ts
> +                        end: getUnixTime(endOfDay(addDays(beginDate, -1))),
为什么加 endOfDay 呢，取 beginDate 前一天的 00:00:00 和 23:59:59 好像没区别

2023-07-07 09:54 UTC, Guoxiin commented on src/date-range/date-range.component.ts
> +                            end: getUnixTime(endOfDay(addMonths(endDate, 1 * interval))),
startOfDay、endOfDay 同上

2023-07-07 09:54 UTC, Guoxiin commented on src/date-range/date-range.component.ts
> +                            begin: getUnixTime(addMonths(beginDate, 1 * interval)),
无论是不是beginIsFirstDayOfMonth && endIsEndDayOfMonth，begin 都可以取 endDate 的下一天

2023-07-07 09:54 UTC, Guoxiin commented on src/date-range/date-range.component.ts
> +                    } else {
只需要通过判读是不是 endIsEndDayOfMonth，是 end 就 endDate 加一个月并取月底那天，不是 end 就只加一个月

2023-07-07 12:34 UTC, minlovehua commented on src/date-range/date-range.component.ts
> +                        end: getUnixTime(endOfDay(addDays(beginDate, -1))),
这里有区别，如果不加 endOfDay 的话，不能保证时间值的精确连贯性。

比如，当前值时  2023-07-01 00:00:00 ~ 2023-07-31 23:59:59
begin: getUnixTime(startOfMonth(new Date())),  
getUnixTime(endOfMonth(new Date())),


点击左侧按钮后，正确的时间值应该是
2023-06-01 00:00:00 ~ 2023-06-30 23:59:59


如果没有 endOfDay，会导致时间值没有精确连贯
2023-06-01 00:00:00 ~ 2023-06-30 00:00:00

2023-07-10 03:18 UTC, Guoxiin approved these changes

2023-07-10 03:18 UTC, merged