feat(flexibleText): #INFR-7980 thy-flexible-text 使用 ThyTooltipService…
atinc/ngx-tethys pull request #2742
Opened 2023-06-27 09:47 UTC by mengshuicmq

… 代替 TooltipService

2023-07-13 05:36 UTC, minlovehua requested changes

2023-07-13 05:36 UTC, minlovehua commented on src/flexible-text/flexible-text.component.ts
> +        this.thyTooltipDirective = new ThyTooltipDirective(
this.tooltipRef = this.thyTooltipService.create(this.elementRef, {
         viewContainerRef: this.viewContainerRef,
         placement: this.placement,
         offset: this.offset,
         hasBackdrop: this.trigger === 'click',
         // ...
});

2023-07-13 05:36 UTC, minlovehua commented on src/flexible-text/flexible-text.component.ts
> +        this.attachTooltip();
重命名为 createTooltipRef ，或者不需要新增 attachTooltip 方法

2023-07-13 05:36 UTC, minlovehua commented on src/flexible-text/flexible-text.component.ts
> +            this.thyTooltipDirective.placement = this.placement;
下面这些都移除掉，不需要了：

<img width="464" alt="image" src="https://github.com/atinc/ngx-tethys/assets/28333707/cb6dfeb6-0f4b-4370-868d-9a18940873d8">

2023-07-13 05:36 UTC, minlovehua commented on src/flexible-text/flexible-text.component.ts
> +        this.thyTooltipDirective.ngOnDestroy();
this.tooltipRef?.dispose();

2023-07-13 05:36 UTC, minlovehua commented on src/flexible-text/flexible-text.component.ts
> +        this.thyTooltipDirective.thyTooltipDisabled = !this.isOverflow;
不需要依赖 thyTooltipDirective 指令了，移除

2023-07-13 05:36 UTC, minlovehua commented on src/flexible-text/flexible-text.component.ts
>              this.isOverflow = false;
删除 isOverflow 变量。
使用 this.tooltipRef.show(this.content); 替代  this.isOverflow=true 
使用 this.tooltipRef.hide(); 替代 this.isOverflow = false;

2023-08-01 08:52 UTC, mengshuicmq commented on src/flexible-text/examples/trigger/trigger.component.html
示例已跟设计师确认
![image](https://github.com/atinc/ngx-tethys/assets/13193164/4e51fce6-cf4d-4286-81d4-1f4aff00c61a)

2023-08-01 09:24 UTC, walkerkay reviewed
实现没问题，Demo感觉可以再优化优化

2023-08-01 09:24 UTC, walkerkay commented on src/flexible-text/examples/trigger/trigger.component.html
> +<div class="d-flex">
这个Demo叫 Trigger 不是特别好，可以是 WithTooltip

2023-08-01 09:24 UTC, walkerkay commented on src/flexible-text/examples/trigger/trigger.component.html
> +  <span>触发方式分为：</span>
我看了看Demo 感觉这个Demo布局不太好，你在考虑考虑优化一下

2023-08-01 09:32 UTC, walkerkay commented on src/flexible-text/examples/trigger/trigger.component.html
> 示例已跟设计师确认 ![image](https://user-images.githubusercontent.com/13193164/257459678-4e51fce6-cf4d-4286-81d4-1f4aff00c61a.png)

文案优化为：Feedback 的触发方式有三种
既然已经加了 Label 了， 就别加「、」了，加个空格隔开就可以了

2023-08-07 10:33 UTC, merged