fix: add tabIndex
atinc/ngx-tethys pull request #2829
Opened 2023-08-31 10:47 UTC by cmm-va

2023-09-01 09:34 UTC, cmm-va commented
1、_MixinBase 好多地方都在用，然后我把它移到core 里了 ；
2、colorPicker 支持了 thyDisabled ；
3、其他的就是只要能做表单元素的，我都加了tabindex ，为了 focus滚动，一部分没有加到host 的 tabindex, 比如slider ， 为了选中的时候 ，foucus 样式应该在pointer 上 ，而不是一个大长方框

2023-09-01 10:07 UTC, why520crazy requested changes
涉及到新增 tabindex 的组件最好补充一下测试
1. 测试默认的 tabindex 有默认值
2. 设置 tabindex 可以生效

2023-09-01 10:07 UTC, why520crazy commented on src/core/overlay/overlay.directive.ts
> +export abstract class ThyOverlayDirectiveBase extends _MixinBase {
建议 ThyOverlayDirectiveBase 不要继承 _MixinBase，因为不是所有的 ThyOverlayDirectiveBase 都是表单元素，目前看只有 ColorPicker 是，我建议尝试一下 ColorPicker 采用继承 mixinTabIndex(mixinDisabled(ThyOverlayDirectiveBase)) 的方式试一下是否可以单独让 ColorPicker 组合多个类

2023-09-04 06:22 UTC, cmm-va commented
1、修改名称为 TabIndexDisabledControlValueAccessorMixin；
2、mixinUnsubscribe(MixinBase) 集中到 mixin；
3、修改 colorPicker 继承

2023-09-04 09:05 UTC, why520crazy requested changes
你这次不是主要加了 ColorPicker、Radio、Chekbox、Rate、Slider、Switch 等组件的 tabindex 么？ 那么建议表单的示例加一下没有的组件，然后按 TabIndex 的时候可以聚焦，且聚焦的样式是主色边框高亮，现在的样式不对，组件不全

2023-09-04 09:06 UTC, why520crazy commented
我发现你改着改着在重构 Mixin 的代码，而不是在做这个工作项最重要的事情了。。。

2023-09-04 10:06 UTC, cmm-va commented
> 我发现你改着改着在重构 Mixin 的代码，而不是在做这个工作项最重要的事情了。。。
哎   我这也是毛病呀  我全局搜索 MixinBase 改成TabIndexDisabledControlValueAccessorMixin， 我一搜看到这么多重复的 UnsubscribeMixin， 我就没忍住改了

2023-09-04 10:13 UTC, cmm-va commented on src/color-picker/color-picker.component.ts
> +    protected onChangeFn: (value: number | string) => void = () => {};
我没继承 AbstractControlValueAccessor

2023-09-04 13:08 UTC, why520crazy commented
有重构的想法是值得鼓励的，还是需要把这个核心的功能完善做好。
或者单独再加一个重构的任务，等做完后再回头做，就怕重构了半天还是有问题的重构……

2023-09-05 03:15 UTC, cmm-va commented
1、 去掉了 UnsubscribeMixin ；
2、 修改了聚焦样式，跟王老师已经对过；

2023-09-05 07:42 UTC, why520crazy reviewed
1. Checkbox 多加一些示例，看一下不对齐的原因
2. Rate、Switch 等不常用的组件放在示例后面
3. ColorPicker 选择颜色不显示且选择后没有聚焦，保证关闭后按 Tab 会继续下一个元素
4. Slider 点击的时候应该自动聚焦， tabindex="0" 设置到最外层元素上
5. Radio Button 应该和 Radio 行为一样（可选，如果很复杂就先不要做了）

2023-09-05 07:42 UTC, why520crazy commented on src/slider/slider.scss
> +                    outline: 0 !important;
这个 outline: 加 !important 做什么？不加不会起作用吗？

下面的样式类似，如果可以去掉建议去掉

2023-09-07 05:53 UTC, merged