feat(date-picker): add event thyDateChange and deprecated shortcutValueChange #INFR-9829
atinc/ngx-tethys pull request #2865
Opened 2023-10-30 02:37 UTC by su4g

2023-10-31 03:51 UTC, walkerkay commented on src/date-picker/date-picker.component.spec.ts
> +        // it('should emit thyDateChange after', fakeAsync(() => {
这块就直接去掉吧

2023-10-31 03:51 UTC, walkerkay commented on src/date-picker/date-picker.component.spec.ts
> +            expect(result).not.toEqual(jasmine.objectContaining({ triggerPresets: jasmine.anything() }));
我理解你这个 case 是要测试如果手动选择时间时，event 不包含   triggerPresets 对吧？ 那我建议你别用 not了 不太好理解，  就直接  expect(result).toEqual(jasmine.objectContaining({ value:xxxx }));  就可以了吧

2023-10-31 05:51 UTC, su4g commented on src/date-picker/date-picker.component.spec.ts
> +        // it('should emit thyDateChange after', fakeAsync(() => {
> 这块就直接去掉吧

我把 date-picker.directive 的测试删除掉，全部放在 date-picker.component 这样可以吗？我理解还是重复测试的问题，week 、year 的 thyDateChange support 这些算重复吗？

2023-10-31 05:52 UTC, su4g commented on src/date-picker/date-picker.component.spec.ts
> +            expect(result).not.toEqual(jasmine.objectContaining({ triggerPresets: jasmine.anything() }));
> 我理解你这个 case 是要测试如果手动选择时间时，event 不包含 triggerPresets 对吧？ 那我建议你别用 not了 不太好理解， 就直接 expect(result).toEqual(jasmine.objectContaining({ value:xxxx })); 就可以了吧

好的

2023-10-31 06:00 UTC, walkerkay commented on src/date-picker/date-picker.component.spec.ts
> +        // it('should emit thyDateChange after', fakeAsync(() => {
> > 这块就直接去掉吧
> 
> 我把 date-picker.directive 的测试删除掉，全部放在 date-picker.component 这样可以吗？我理解还是重复测试的问题，week 、year 的 thyDateChange support 这些算重复吗？

我的意思是不用注释了 直接去掉吧

2023-10-31 06:21 UTC, su4g commented on src/date-picker/date-picker.component.spec.ts
> +        // it('should emit thyDateChange after', fakeAsync(() => {
> > > 这块就直接去掉吧
> > 
> > 
> > 我把 date-picker.directive 的测试删除掉，全部放在 date-picker.component 这样可以吗？我理解还是重复测试的问题，week 、year 的 thyDateChange support 这些算重复吗？
> 
> 我的意思是不用注释了 直接去掉吧

好的，已经处理了

2023-10-31 06:53 UTC, why520crazy requested changes

2023-10-31 06:53 UTC, why520crazy commented on src/date-picker/standard-types.ts
> +    triggerPresets?: ThyShortcutPreset;
triggerPresets => triggerPreset

2023-11-01 02:29 UTC, walkerkay approved these changes

2023-11-02 02:37 UTC, merged