Ng9 update
atinc/ngx-tethys pull request #959
Opened 2020-11-18 10:30 UTC by wszgrcy

2020-11-22 06:16 UTC, why520crazy requested changes

2020-11-22 06:16 UTC, why520crazy commented on src/grid/grid.component.ts
> +            console.log('设置hover', this.className);
Remove Console.log

2020-11-22 06:16 UTC, why520crazy commented on src/grid/grid.component.ts
> +        this.className = list.join(' ');
这里修改主要目的是什么？这个和升级没有关系，建议从这个 PR 去掉，重新提一个修复 Grid Class Name 的 PR

2020-11-23 02:04 UTC, wszgrcy commented on src/grid/grid.component.ts
> +        this.className = list.join(' ');
这个是因为升级Ng9后好像生命周期变化了,导致单元测试不通过(因为会先执行一些状态类的添加后设置类,导致状态类被覆盖了)
另外先别合并了,我先把业务组件库跑通,然后找一个demo跑通后再合吧

2020-11-27 03:28 UTC, closed without merging